using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace DataDisplaySample {
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window {
        public MainWindow() {
            InitializeComponent();

            var data = new ObservableCollection<Person>(
                Enumerable.Range(1, 100).Select(i => new Person {
                    Name = "田中　太郎" +i,
                    Gender = i % 2 == 0 ? Gender.Men : Gender.Women,
                    Age = 20 + i % 50,
                    AuthMember = i % 5 == 0
                }));
            this.dataGrid.ItemsSource = data;
            this.dataGrid2.ItemsSource = data;
        }

        private void dataGrid_AutoGeneratedColumns(object sender, DataGridAutoGeneratingColumnEventArgs e) {

        }

        private void dataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e) {
            switch (e.PropertyName) {
                case "Name":
                    e.Column.Header = "名前";
                    e.Column.DisplayIndex = 0;
                    break;
                case "Age":
                    e.Column.Header = "年齢";
                    e.Column.DisplayIndex = 1;
                    break;
                case "Gender":
                    e.Cancel = true;
                    break;
                case "AuthMember":
                    e.Column.Header = "承認済み";
                    e.Column.DisplayIndex = 2;
                    break;

                default:
                    throw new InvalidOperationException();
            }
        }
    }
}
